name: Sync labels

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/labels.yml"

permissions:
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync repository labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
